## Use this notebook to take water bodies from the HydroPolys layer, match them to the gauge data and add them to the Named_Reservoirs shapefile

In [1]:
%matplotlib inline

import sys

sys.path.append('Scripts')
from datahandling import wofs_fuser

import datacube
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt
from pathlib import Path
from datacube.utils import masking
from datacube.utils import geometry 
from datacube.utils.geometry import CRS
from datacube.helpers import write_geotiff
import geopandas as gpd
import ipyleaflet as ipyl
import ipywidgets as ipyw
import json



dc = datacube.Datacube()

/env/lib/python3.6/site-packages/geopandas/_compat.py:88: UserWarning: The Shapely GEOS version (3.7.2-CAPI-1.11.0 ) is incompatible with the GEOS version PyGEOS was compiled with (3.9.0-CAPI-1.16.2). Conversions between both will be slow.
  shapely_geos_version, geos_capi_version_string

## Read and fomat the polygon you want to add to the Named_Reservoirs shapefile

In [12]:
csv = 'Library/'
gdf = gpd.read_file('HydroPolys/BLUE_ROCK.shp')
gdf

,FEATURETYP,TYPE,NAME,PERENNIALI,HIERARCHY,DIMENSION,FEATUREREL,FEATURESOU,ATTRIBUTER,ATTRIBUTES,PLANIMETRI,GAID,AUSHYDRO_I,STKEHDRID,STKEHDRNAM,SHAPE_Leng,SHAPE_Area,NATURE,WATERSTORA,geometry
0,Lake,6,BLUE ROCK LAKE,Perennial,None,8558204.0,1999-01-01,DSE,1999-01-01,DSE,20,6391553,6391553,13783370,DSE,0.481989,0.000879,None,None,"POLYGON ((146.19996 -38.02685, 146.20021 -38.0..."

In [13]:
#Get the centroid location of the reservoir

gdf = gdf.to_crs(epsg=4326) #4326 is the tag for lat lon format
#we need to get the lat and lon of where the dam is to call the right satellite data later
#we want the lat and lon to be columns in the data to make it easy when we query the wofs data later
#Getting the centroid from the polygon and adding a latitude and longitude column (I found this code on the internet):
def getXY(pt):
    return (pt.x, pt.y)
centroidseries = gdf['geometry'].centroid
x,y = [list(t) for t in zip(*map(getXY, centroidseries))]

gdf = gdf.assign(lon=x)
gdf = gdf.assign(lat=y)
gdf = gdf[['NAME', 'SHAPE_Leng', 'SHAPE_Area', 'lat', 'lon', 'geometry']]
gdf

/env/lib/python3.6/site-packages/ipykernel_launcher.py:9: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  if __name__ == '__main__':

,NAME,SHAPE_Leng,SHAPE_Area,lat,lon,geometry
0,BLUE ROCK LAKE,0.481989,0.000879,-38.061382,146.20039,"POLYGON ((146.19996 -38.02685, 146.20021 -38.0..."

In [14]:
gauge_number_df = pd.read_csv(csv, nrows=3, escapechar='#')
column2 = list(gauge_number_df)[1]
gauge_number_df = gauge_number_df.rename(columns = {column2 : 'gauge_ID'})
ID_str = gauge_number_df.at[0, 'gauge_ID']
#ID_str = ID_str.astype(int)
#ID_str = ID_str.astype(str)
lat = gauge_number_df.at[1, 'gauge_ID']
lon = gauge_number_df.at[2, 'gauge_ID']
gdf['gauge_ID'] = ID_str
gdf['lat_gauge'] = lat
gdf['lon_gauge'] = lon
gdf['Area_calc'] = ''
gdf['staion_nam'] = column2
gdf = gdf[['NAME', 'SHAPE_Leng', 'SHAPE_Area', 'lat', 'lon', 'Area_calc', 'staion_nam', 'gauge_ID', 'lat_gauge', 'lon_gauge', 'geometry']]
gdf

,NAME,SHAPE_Leng,SHAPE_Area,lat,lon,Area_calc,staion_nam,gauge_ID,lat_gauge,lon_gauge,geometry
0,BLUE ROCK LAKE,0.481989,0.000879,-38.061382,146.20039,,TANJIL RIVER @ BLUE ROCK LAKE (HEAD GAUGE),226230A,-38.07768889,146.2279389,"POLYGON ((146.19996 -38.02685, 146.20021 -38.0..."

In [15]:
gdf2 = gpd.read_file('Named_Reservoirs/Named_Reservoirs9.shp')
gdf2 = gdf2.to_crs(epsg=4326)
gdf2.tail()

,NAME,SHAPE_Leng,SHAPE_Area,lat,lon,Area_calc,staion_nam,gauge_ID,lat_gauge,lon_gauge,geometry
423,MARIAN WEIR,0.266732,0.000134,-21.146641,148.885758,1544632.18,Mirani Weir HW,125008A,-21.17788,148.83,"POLYGON ((148.82987 -21.17723, 148.82926 -21.1..."
424,TINANA BARRAGE,0.034002,0.000012,-25.571684,152.713346,129235.966,Tinana Barrage HW,138008A,-25.57206,152.7181,"POLYGON ((152.71974 -25.56929, 152.71973 -25.5..."
425,LAKE GLENMAGGIE,0.550671,0.001746,-37.906605,146.768497,None,MACALISTER RIVER @ LAKE GLENMAGGIE (HEAD GAUGE),225225A,-37.90833333,146.8,"POLYGON ((146.72768 -37.85241, 146.72792 -37.8..."
426,MURRAY 2 PONDAGE,0.054875,0.000014,-36.241612,148.185751,None,Khancoban Back Creek at Murray 2 Pondage,401571,-36.23772778,148.18115278,"POLYGON ((148.18139 -36.24036, 148.18151 -36.2..."
427,DUNHAM PILOT DAM,0.313080,0.000950,-16.032589,128.363891,None,DUNHAM PILOT DAM,DPD.Q,-16.032589,128.363891,"POLYGON ((128.34413 -16.06702, 128.34413 -16.0..."

In [16]:
gdf3 = gdf2.append(gdf)
gdf3.tail()

,NAME,SHAPE_Leng,SHAPE_Area,lat,lon,Area_calc,staion_nam,gauge_ID,lat_gauge,lon_gauge,geometry
424,TINANA BARRAGE,0.034002,0.000012,-25.571684,152.713346,129235.966,Tinana Barrage HW,138008A,-25.57206,152.7181,"POLYGON ((152.71974 -25.56929, 152.71973 -25.5..."
425,LAKE GLENMAGGIE,0.550671,0.001746,-37.906605,146.768497,None,MACALISTER RIVER @ LAKE GLENMAGGIE (HEAD GAUGE),225225A,-37.90833333,146.8,"POLYGON ((146.72768 -37.85241, 146.72792 -37.8..."
426,MURRAY 2 PONDAGE,0.054875,0.000014,-36.241612,148.185751,None,Khancoban Back Creek at Murray 2 Pondage,401571,-36.23772778,148.18115278,"POLYGON ((148.18139 -36.24036, 148.18151 -36.2..."
427,DUNHAM PILOT DAM,0.313080,0.000950,-16.032589,128.363891,None,DUNHAM PILOT DAM,DPD.Q,-16.032589,128.363891,"POLYGON ((128.34413 -16.06702, 128.34413 -16.0..."
0,BLUE ROCK LAKE,0.481989,0.000879,-38.061382,146.200390,,TANJIL RIVER @ BLUE ROCK LAKE (HEAD GAUGE),226230A,-38.07768889,146.2279389,"POLYGON ((146.19996 -38.02685, 146.20021 -38.0..."

In [17]:
gdf3.to_file('Named_Reservoirs/Named_Reservoirs9.shp')